### ISSUE TITLE
Feature request: Move wordlist to configuration file enabling sync between devices

### ISSUE THREAD

**Issue by jakobhviid** [yzhang-gh/vscode-dic-completion#11]
Hello!

I would like to request moving the wordlist (custom words) to the VSCode configuration file as it would enable using sync applications (such as https://github.com/shanalikhan/code-settings-sync) to sync your custom words between devices. 

Moving to the configuration file would also allow for project specific words, or editor wide words.

Current implementation of a wordlist could stay, and allow importing words from both sources as an option, as to not break compatibility with previous implementation.

This is literally the biggest problem for me as i move between many devices, and i use time syncing the wordlist.

Thanks for making this great extension!

**Comment by yzhang-gh** [comment]
As far as I know, you seem to be able sync custom files with settings [here](https://github.com/shanalikhan/code-settings-sync#global-settings) (`supportedFileExtensions`, I haven't tested).

**Comment by jakobhviid** [comment]
Hi. 

Thank you very much for the suggestion. I have tried several times, but without luck. 
I think the problem relates to the fact i am using multiple operating systems. I use windows, mac and sometimes linux too. 
So, i am back here hoping for the option to keep words in a settings list.

Also, enabling custom words in settings would allow multiple users to sync their words for a project to the other developers of a project too, as a user has the "workspace" settings, and "editor" settings.

Thank you for your time.

**Comment by yzhang-gh** [comment]
Sorry I didn't remember the right link last time. It should be [Custom Sync](https://github.com/shanalikhan/code-settings-sync/wiki/Custom-Sync). (I have used it to sync my custom spell checker wordlist)

But I am willing to get it a try to make use of the user settings tonight. Get back to you later.

**Comment by jakobhviid** [comment]
Thank you! I found the correct link, don't worry.

**Comment by yzhang-gh** [comment]
Could you help test the [dev build](https://ci.appveyor.com/project/yzhang-gh/vscode-dic-completion/build/artifacts)? There are two new options `useExternalUserDictFile` and `userDictionary`.

**Comment by jakobhviid** [comment]
Sure!.

I have tested the extension by adding the following to the settings file:


```json
{
    "dictCompletion.userDictionary": [
        "qwertyuiop",
        "asdfghjklæø"
    ],
    "dictCompletion.UseExternalUserDictFile": false
}
```

I also tested it in the /.vscode/settings.json file, as well on windows and a mac. Everything seems to work as expected!

Thank you for taking the time to implement this feature!

**Comment by yzhang-gh** [comment]
Oops, the setting name should have been `useExternalUserDictFile` 😂. I'll change it and publish a new version.
