### ISSUE TITLE
Feature Request: Also use words from codespell settings

### ISSUE THREAD

**Issue by jakobhviid** [yzhang-gh/vscode-dic-completion#12]
Hi.

After you kindly implemented the option to add custom words to, it became obvious to me that most, but not all, words are duplicated in the Code Spell Extension settings that looks like this:

```json
{
  "cSpell.userWords": [
    "Bosswave",
    "Fierro",
    "Fuseki",
    "GDPR",
    "Hviid",
    "Nellemann",
    "OccuRE",
    "SMAP",
    "XBOS",,
    "blockchain",
    "chktex",
    "failover",
    "microservice",
    "microservices",
    "reconfiguring",
    "subfield",
    "subfields"
  ]
}
```

For this reason, i propose adding a setting for reading the cspell.userWords setting too for auto completion purposes. So, when a user adds a word to code spell, it can automatically be added to the autocomplete suggestion list.

It is just a string array, so i imagine it is trivial to add to the functionality you already created when reading from the settings list. I imagine a "dictCompletion.useCodeSpellUserWords": true as an option.

This would cleanup the settings files immensely as words are not duplicated between the setting lists, and would allow the user to do less maintenance of the wordlist manually, as relevant words gets added automatically over time.

Let me know what you think.

**Comment by yzhang-gh** [comment]
This is trivial. The only problem is my laptop was broken yesterday...

**Comment by jakobhviid** [comment]
I am sad to hear of your problems with your laptop. I hope you get it resolved soon.

The feature is fortunately not time sensitive, and less essential than the other feature you implemented.

**Comment by yzhang-gh** [comment]
Please see the [dev build](https://ci.appveyor.com/project/yzhang-gh/vscode-dic-completion/build/artifacts).

**Comment by jakobhviid** [comment]
I can confirm it works as expected! Thank you!

**Comment by jakobhviid** [comment]
Hello. Do you have an ETA of when this is moving to the VS Code marketplace?

**Comment by yzhang-gh** [comment]
Probably this weekend

**Comment by jakobhviid** [comment]
From what i can see, this still has not gone into the official extension. Any chance you have time to look at it soon?

**Comment by yzhang-gh** [comment]
Oops, thanks for the reminder. It should get updated now.

**Comment by jakobhviid** [comment]
You are welcome. And thank you!
