### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by JounQin** [yzhang-gh/vscode-dic-completion#17]
- Issue Type: `Performance`
- Extension Name: `dictionary-completion`
- Extension Version: `0.8.3`
- OS Version: `Darwin x64 18.7.0`
- VSCode version: `1.38.1`

[yzhang.dictionary-completion-unresponsive.cpuprofile.txt](https://github.com/yzhang-gh/vscode-dic-completion/files/3640718/yzhang.dictionary-completion-unresponsive.cpuprofile.txt)

**Comment by yzhang-gh** [comment]
![image](https://user-images.githubusercontent.com/7588612/65408989-39654e80-de19-11e9-855f-784234f4b712.png)

I don't see any problem from the CPU profile. The costliest extension function call takes less than 0.1s.

Feel free to reopen this if you still have this issue (and more information).
