### ISSUE TITLE
Feature Request: support all file types

### ISSUE THREAD

**Issue by elrrrrrrr** [yzhang-gh/vscode-dic-completion#18]
Currently only supports a few files, Is there any plan to support more file types.

**Comment by yzhang-gh** [comment]
What file types would you like to support?

**Comment by elrrrrrrr** [comment]
@yzhang-gh 
such as jsx, js and css file.
Now I use [all autocomplete](https://marketplace.visualstudio.com/items?itemName=Atishay-Jain.All-Autocomplete) and dic-complteion these two plugin to implement this feature which seems a little complex.

**Comment by yzhang-gh** [comment]
The concern is I try avoiding unwanted completions in certain contexts. For example,

https://github.com/yzhang-gh/vscode-dic-completion/blob/26a131340e14e0085c2a4da4514176a85d2d7158/src/completion.ts#L154-L155

https://github.com/yzhang-gh/vscode-dic-completion/blob/26a131340e14e0085c2a4da4514176a85d2d7158/src/completion.ts#L160-L162

https://github.com/yzhang-gh/vscode-dic-completion/blob/26a131340e14e0085c2a4da4514176a85d2d7158/src/completion.ts#L175-L176

In JS or CSS files, only strings and comments may need completions from the English dictionary.
Are you requesting this?

**Comment by elrrrrrrr** [comment]
I used the coc.nvim plugin to provide some common word completions, no matter which file type.
Is it possible to add some arguments to support specified file types, in code context?

![image](https://user-images.githubusercontent.com/5574625/67353440-2ca55900-f585-11e9-936a-f94f6e40ab90.png)

**Comment by yzhang-gh** [comment]
我感觉我的意思没有表达很清楚😂

这个插件的目标是：只在写作（并且非编程环境）的时候提供单词补全
而在编程的时候，变量名往往并不是一个单词（可能是缩写 `tmp`，或者多个单词复合 `getWorkspace`），纯单词补全不但没什么意义反而还增加了噪音 
唯一能用上的地方就是字符串或者注释中

看起来你的希望是 在所有文件中的所有地方都提供单词补全
我个人感觉逻辑上和这个插件本身不合

**现在是**
![image](https://user-images.githubusercontent.com/7588612/67358434-f2db4f00-f592-11e9-83f7-3cc5c4ccca80.png)
和
![image](https://user-images.githubusercontent.com/7588612/67358444-fe2e7a80-f592-11e9-9ad6-c192a2311bef.png)

**改之后**
![image](https://user-images.githubusercontent.com/7588612/67358386-c9222800-f592-11e9-8df0-85e8d444d456.png)

**Comment by elrrrrrrr** [comment]
了解啦 ^ ^
感谢 🙆

**Comment by yzhang-gh** [comment]
噔噔，v0.9.1 增加了对编程语言的支持（在注释或字符串中提供补全）. 看起来之前你是在写 JS，那就可以用这个新功能啦.
