### ISSUE TITLE
[Feature] Enable in string and comment of JS/Python etc.

### ISSUE THREAD

**Issue by DearVikki** [yzhang-gh/vscode-dic-completion#24]
我理解是敲下一个字母 就会出现下拉菜单显示可选单词的对吗？比如 a => abandon 这样…
但是我安装后敲单词时依旧没提示，请问是我的理解错误，还是用法不对呢？😳

vscode version: 1.44.2

**Comment by yzhang-gh** [comment]
你是在 Markdown 里编辑吗？如果是的话得修改一个设置（README 里有写）
```
"[markdown]": {
    "editor.quickSuggestions": true
}
```

（BTW，偶然看到了你的个人主页，很有趣🤪

**Comment by DearVikki** [comment]
不好意思没注意到你的回复，你看，我敲英文没有给出单词提示呀
![ezgif-3-9f47bb35de41](https://user-images.githubusercontent.com/18145936/85094282-0376be80-b221-11ea-93a5-b9f1715dc855.gif)

（哈哈哈谢谢，那还是多年前的入门时期，现在我变强了，想象力也枯竭了 😢

**Comment by yzhang-gh** [comment]
看到图我就明白了，因为目前只支持 Markdown，LaTeX 和 HTML（的非 tag 之内的区域），并不支持 JS。

在编程语言的字符串和注释中支持补全倒确实是一个有用的特性。
