### ISSUE TITLE
Include default autocompletion results

### ISSUE THREAD

**Issue by anishmittal2020** [yzhang-gh/vscode-dic-completion#26]
Vscode by default have autocompletions which shows a list of already used words (in the file). As it is more likely that an already used word is used again. These words don't have to be in the dictionary.

# Request

1. Is it possible to have an option to enable the default autocompletion of vscode results that could show before the results of dictionary. 
2. May be it would also be better to have a keyboard shortcut to disable or enable it.

**Comment by yzhang-gh** [comment]
Let's track this at #22.
