### ISSUE TITLE
希望可以添加对vue文件的支持

### ISSUE THREAD

**Issue by jipika** [yzhang-gh/vscode-dic-completion#39]
感谢大佬的付出哇，球球添加对vue文件的支持🤧

**Comment by yzhang-gh** [comment]
这个已经被很多人请求过了，所以这次很粗糙地添加了对 Vue 的支持，可以到 https://github.com/yzhang-gh/vscode-dic-completion/actions/runs/2314239406 下载开发版本尝鲜

related #27, #36
