### ISSUE TITLE
Support for the `.todo` files

### ISSUE THREAD

**Issue by yinsn** [yzhang-gh/vscode-dic-completion#41]
Thanks for your great work in this `vscode-dic-completion`!
In my daily life, I also use the `vscode-todo-plus` extension to manage my daily tasks:
[vscode-todo-plus repo](https://github.com/fabiospampinato/vscode-todo-plus)
 would you possible for you to support this `.todo` files or `.txt` files as well? Thanks!

**Comment by yzhang-gh** [comment]
Thanks.

I haven't tested it but you can try out the [dev build](https://github.com/yzhang-gh/vscode-dic-completion/actions/runs/3711895142) (under the Artifacts section).

**Comment by yinsn** [comment]
Marvelous! It works for the `.todo` file! Thanks your so much!
