### ISSUE TITLE
`morphology` is misspelled as `morphololgy` in the dictionary file

### ISSUE THREAD

**Issue by CastleStar14654** [yzhang-gh/vscode-dic-completion#51]
Here, this word is misspelled:
https://github.com/yzhang-gh/vscode-dic-completion/blob/07fc813855ebe39ffb63385b5aeec568c5a3f41d/words#L4824

**Comment by yzhang-gh** [comment]
Many thanks.

The dev build can be downloaded in https://github.com/yzhang-gh/vscode-dic-completion/actions/runs/9697793002 (Artifacts section)
