### ISSUE TITLE
Feature Request: Support for custom abbreviations

### ISSUE THREAD

**Issue by tecosaur** [yzhang-gh/vscode-dic-completion#6]
### 1. [Simple-ish]

The ability to have custom words in a dictionary file / split into multiple named files. For example, I have a section of molecular bio words, and it would be nice to have a way to clearly separate it from other stuff.

_(My ideas for) Implementation_: Add a comment/escape character **or** allow custom, names, user direct files. Perhaps a folder containing these which are combined to one file (i.e. the current user dict. file)
 
### 2. [less simple, probably]

Sometimes there's a long word that I may use a bit that I want to add to the dictionary, such as "dideoxynucleotide". However, it (and quite a few other words) also have a much shorter abbreviation. In this example "ddNTP". It would be quite handy if there would be some easy way of adding abbreviations that can suggest an associated word, ideally with the option of competing with the abbreviation with the abbreviation too. 

_(My ideas for) Implementation_: Non-common Unicode character in user dict. file to represent this, i.e. "→", or to pick a less common one one of these  "⟶ ↦ ⤍ ⤏ ⟾" which is added via a simple shortcut which is only active when editing those files (can this be done?) and will allow a format like "abbr → word", with usage- insert abbreviation/full word by default with modifier key using other (with setting to change which is the default) **or** something like an extra json file.

#### Sorry that this is a half-baked. Though it was worth mentioning these though.

**Comment by neilsustc** [comment]
I have added support to comment support (`//`).

For point 2, it can be implemented with [code snippets](https://code.visualstudio.com/docs/extensionAPI/language-support#_source-code-snippets).

![image](https://user-images.githubusercontent.com/7588612/44630375-ea878400-a98e-11e8-9fd4-7ce976485174.png)

But I will travel during the next week. If someone is interested in implementing this, that will be great.

One example is available [here](https://github.com/neilsustc/vscode-markdown/blob/master/src/completion.ts). You can see how `mathCompletion` code snippets are constructed.

**Comment by tecosaur** [comment]
Thanks for the speedy response 😃

For point 2 - I personally would like to avoid using code snippets as I like to keep my code stuff separate to my just-writing-text stuff, and I know I'd find the ability to switch between abbreviation and full word completion useful. But thanks for reminding me :)

I'll __potentially__ take a look at implementing it myself at an indeterminate point in the future (possibly next weekend) depending on stuff like difficulty/available time

**Comment by neilsustc** [comment]
(I forgot to mention that you could already download the CI build from [here](https://ci.appveyor.com/project/neilsustc/vscode-dic-completion/build/artifacts), which includes the comment support)

**Comment by tecosaur** [comment]
I'll just close this for now
